### ISSUE TITLE
Could you help me a bit, what am I doing wrong?

### ISSUE THREAD

**Issue by dv-petrov** [hkato/migrate_from_trac.rake#1]
I am not very familiar with Rails. When I run the rake script, I get "Don't know how to build task 'environment'".
When I remove "=> :environment" from script, I get "uninitialized constant TracMigrate::IssueStatus".

**Comment by hkato** [comment]
Did you solve? @eldhenn

**Comment by dv-petrov** [comment]
Yes. The point was "copy rake file to redmine/lib/tasks".
