### ISSUE TITLE
Commits and issues links

### ISSUE THREAD

**Issue by dv-petrov** [hkato/migrate_from_trac.rake#2]
Did you get worked links between old commits (which have messages like "Fixed BUG#1") and gitlab migrated issues?

**Comment by hkato** [comment]
> messages like "Fixed BUG#1"

Do you mean history of `migrate_from_trac.rake`? please refer to the Redmine issue # in the `README.md`.

>gitlab migrated issues?

This project has nothing to do with GitLab.
